
params ["_module"];

RADIOCOMMS_OBJECTS_WITH_COMMS = _module getVariable "ObjectsWithComms";
if (RADIOCOMMS_OBJECTS_WITH_COMMS isEqualType "") then { RADIOCOMMS_OBJECTS_WITH_COMMS = call compile RADIOCOMMS_OBJECTS_WITH_COMMS; };

RADIOCOMMS_AUDIBLE_RADIUS = _module getVariable "AudibleRadius";
if (RADIOCOMMS_AUDIBLE_RADIUS isEqualType "") then { RADIOCOMMS_AUDIBLE_RADIUS = call compile RADIOCOMMS_AUDIBLE_RADIUS; };

RADIOCOMMS_PERSONAL_RADIOS = _module getVariable "PersonalRadios";
if (RADIOCOMMS_PERSONAL_RADIOS isEqualType "") then { RADIOCOMMS_PERSONAL_RADIOS = call compile RADIOCOMMS_PERSONAL_RADIOS; };

RADIOCOMMS_ITEMS_BACKPACKS = _module getVariable "RTOItemsAndBackpacks";
if (RADIOCOMMS_ITEMS_BACKPACKS isEqualType "") then { RADIOCOMMS_ITEMS_BACKPACKS = call compile RADIOCOMMS_ITEMS_BACKPACKS; };

RADIOCOMMS_REQUIRE_RANKING_OFFICER = _module getVariable "RequireRankingOfficer";
if (RADIOCOMMS_REQUIRE_RANKING_OFFICER isEqualType "") then { RADIOCOMMS_REQUIRE_RANKING_OFFICER = call compile RADIOCOMMS_REQUIRE_RANKING_OFFICER; };

RADIOCOMMS_ENABLE_BROKEN_ARROW = _module getVariable "EnableBrokenArrow";
if (RADIOCOMMS_ENABLE_BROKEN_ARROW isEqualType "") then { RADIOCOMMS_ENABLE_BROKEN_ARROW = call compile RADIOCOMMS_ENABLE_BROKEN_ARROW; };

